name: Update Auth Token and Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set AUTH_TOKEN as environment variable
        run: echo "AUTH_TOKEN=${{ secrets.AUTH_TOKEN }}" >> $GITHUB_ENV    
      - name: Deploy to GitHub Pages
        run:
          echo "Deploying to GitHub Pages with AUTH_TOKEN..."
